### PR TITLE
[NEW] LC 206. Reverse Linked List 

### PR DESCRIPTION
**Pull request by nil1729**

### CODE REVIEW

**Comment by sarthak-sehgal** [comment]
Hi @nil1729, while your code looks good, I think that the blog should give the reader access to all solutions. I'd recommend you to split your article into the following subheadings (or try to clean your code further - see approach 2):
1. My Solution: Iterative, long code
2. Approach 2: Iterative, short code
```
    ListNode* reverseList(ListNode* head) {
        ListNode *prev = NULL;
        while (head) {
            ListNode* temp = head->next;
            head->next = prev;
            prev = head;
            head = temp;
        }
        
        return prev;
    }
```
3. Approach 3: Recursive
Recurse till the end of the list and return the last node. After each function call pop from the recursion stack, reverse the next pointer. See code below:
```
    ListNode* reverseList(ListNode* head) {
        if (!head || !head->next)
            return head;
        ListNode* temp = reverseList(head->next);
        head->next->next = head;
        head->next = NULL;
        return temp;
    }
```
```
Let's say the list is 1->2->3:
Recursion: reverseList(1) -> reverseList(2) -> reverseList(3)
reverseList(3) returns "3"
Then, in the function reverseList(2) function: head is 2. head->next is 3. So head->next->next = head implies 3->next = 2 hence reversing the arrow. head->next= NULL so 2->next = NULL. Now, our list is 1->2<-3

reverseList(2) returns "3" (temp)
Then, in the function reverseList(1): head is 1. head->next is 2. So head->next->next = head imples 2->next = 1 hence reversing the arrow. head->next = NULL implies 1->next = NULL. Now, our list is reversed! 1<-2<-3

reverseList(1) returns "3" (temp) which is the head of our new list.
```

**Comment by sarthak-sehgal** [comment]
Thanks a lot for your contributions, much appreciated!

**Comment by nil1729** [comment]
Can you (@sarthak-sehgal ) please review this commit!

**Comment by sarthak-sehgal** [comment]
Looks great, thanks! 🌟

**Comment by nil1729** [comment]
Thanks(@sarthak-sehgal ), for adding my Contribution to your blog and guide me to solve a problem efficiently

**Pull request merged**
